### ISSUE TITLE
additional phrase possibilities please

### ISSUE THREAD

**Issue by Mcgufa** [gustavbnm/PirateSBingo#9]
7
ADS IN PROGRESS
"Cyber"
You are Allowed to Make Games
Music Stops for Some Serious Stuff
Shay Appearance
Blizzard Life Stories
Make Box Move
"100%"
Work/Sleep Schedule
Bok Choy
Game Jam
Develop.Games
Free Socks
Buy the Heartbound Demo
Don't Quit Your Day Job!
Dad is the WOW Guy South Park
Ferretts
Eat My WHOLE ASS
How to Start Hacking LEGALLY
Rick Roll
Cursed TTS Donation Message
You interacted with my Shorts,  You're stuck with me.
Eagles Per  Gun,  Feet/Centipedes
"Deeply Hilarious"

i believe i don't have any duplicates here.
i think it would be funnier if it was simply "7" rather than "sevens chat"
Hope this is all okay

**Comment by gustavbnm** [comment]
nice 👍 just one duplicate i belive "ADS IN PROGRESS" we already have (b)ADs

**Comment by Neppkun** [comment]
- **7**
Won't change.
- **ADS IN PROGRESS**
Already in as (b)ADs
- **"Cyber"**
Added.
- **"You are allowed to make games"**
Added as "Make a moving box"
- **"100%"**
Added.
- **Work/Sleep Schedule"**
Added.
- **Bok Choy**
Added.
- **Game Jam**
Added.
- **Develop.games**
Kind of already in as "Work on game".
- **Free socks**
Added.
- **Buy the Heartbound demo**
This counts as chat being goblins. Won't add in honor of "Chat is goblins".
- **Don't quit your day job!**
Added.
- **Dad is the WOW Guy South Park**
Already in as "He who has no life".
- **Ferrets**
Added as "Ferret Rescue"
- **Eat my WHOLE ass**
Added as "Eat my entire ass" (that's usually how he says it)
- **How to start hacking legally**
Added as "How to hack legally"
- **Rick Roll**
Won't add. Thor cannot be gnomed, nor can he be rickrolled.
- **Cursed TTS Message**
Added as "Cursed TTS"
- **You interacted with my Shorts, You're stuck with me.**
Too long to add.
- **Eagles per gun**
Added.
- **Deeply Hilarious**
Added.

https://github.com/gustavbnm/PirateSBingo/pull/11
